# Generated by Django 2.2.18 on 2023-05-27 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20230525_1336'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='view',
            field=models.PositiveIntegerField(default=0, verbose_name='阅读数量'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='order',
            field=models.CharField(default=999, max_length=255),
        ),
    ]
