# Generated by Django 2.2.18 on 2023-05-20 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='link_id',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='相关联信息id'),
        ),
    ]
