# Generated by Django 2.2.18 on 2023-05-20 22:25

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('title', models.CharField(default='无标题', max_length=100)),
                ('code_highlight', models.CharField(default='atom', max_length=50, verbose_name='代码高亮模式')),
                ('preview', models.CharField(default='default', max_length=50, verbose_name='markdown模式')),
                ('desc', models.CharField(blank=True, max_length=256, null=True)),
                ('avatar', models.URLField(blank=True, null=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('content', models.TextField()),
                ('add_time', models.DateTimeField(auto_now_add=True)),
                ('view', models.PositiveIntegerField(default=0, verbose_name='阅读数量')),
                ('like', models.PositiveIntegerField(default=0, verbose_name='点赞量')),
                ('comment', models.PositiveIntegerField(default=0, verbose_name='评论量')),
            ],
            options={
                'verbose_name': '文章',
                'verbose_name_plural': '文章',
                'ordering': ('-add_time',),
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('add_time', models.DateTimeField(default=datetime.datetime.now)),
            ],
            options={
                'verbose_name': '分类',
                'verbose_name_plural': '分类',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.TextField(blank=True, null=True)),
                ('object_id', models.CharField(default='s', max_length=128)),
                ('content', models.TextField()),
                ('like', models.PositiveIntegerField(default=0, verbose_name='点赞量')),
                ('comment', models.PositiveIntegerField(default=0, verbose_name='评论量')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Discussion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('image', models.TextField(blank=True, null=True)),
                ('content', models.TextField()),
                ('like', models.PositiveIntegerField(default=0, verbose_name='点赞量')),
                ('comment', models.PositiveIntegerField(default=0, verbose_name='评论量')),
                ('add_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '讨论',
                'verbose_name_plural': '讨论',
                'ordering': ('-add_time',),
            },
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.CharField(max_length=128)),
                ('count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('add_time', models.DateTimeField(default=datetime.datetime.now)),
            ],
            options={
                'verbose_name': '标签',
                'verbose_name_plural': '标签',
            },
        ),
        migrations.CreateModel(
            name='LikeDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('likes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.Like')),
            ],
            options={
                'ordering': ('-date',),
            },
        ),
    ]
